# Generated by Django 3.1.6 on 2021-04-10 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performances', '0002_auto_20210407_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='id',
        ),
        migrations.AlterField(
            model_name='institution',
            name='head_of_institution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
