# Generated by Django 3.1.6 on 2021-04-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0004_auto_20210410_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
