# Generated by Django 3.1.6 on 2021-04-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0005_auto_20210410_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
