# Generated by Django 3.1.6 on 2021-04-19 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performances', '0008_auto_20210419_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='head_of_institution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution_head', to=settings.AUTH_USER_MODEL),
        ),
    ]
