# Generated by Django 3.1.6 on 2021-05-05 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performances', '0011_auto_20210429_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='available',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performance',
            name='group_leader',
            field=models.ForeignKey(help_text='The group leader can be a teacher in charge of a dependent performance or an independent performer leading  an independent performance.', on_delete=django.db.models.deletion.CASCADE, related_name='performance_group_leader', to=settings.AUTH_USER_MODEL),
        ),
    ]
