# Generated by Django 3.1.6 on 2021-06-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0015_auto_20210603_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'class', 'verbose_name_plural': 'classes'},
        ),
        migrations.AlterModelOptions(
            name='locality',
            options={'verbose_name': 'locality', 'verbose_name_plural': 'localities'},
        ),
        migrations.AlterField(
            model_name='performance',
            name='performer_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
