# Generated by Django 3.1.6 on 2021-06-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0018_auto_20210603_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_level',
            field=models.CharField(choices=[('ZONE', 'Zone'), ('SUB-COUNTY', 'Sub-County'), ('COUNTY', 'County'), ('REGION', 'Region'), ('NATION', 'Nation')], max_length=15),
        ),
    ]
