# Generated by Django 3.1.6 on 2021-06-03 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0019_auto_20210603_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='locality',
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performances.institution'),
        ),
    ]
