# Generated by Django 3.1.6 on 2021-03-29 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210329_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependentperformerprofile',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to='accounts.sponsorprofile'),
        ),
    ]
