# Generated by Django 3.1.6 on 2021-04-19 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0008_auto_20210419_0931'),
        ('accounts', '0005_auto_20210407_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependentperformerprofile',
            options={'verbose_name': 'dependent performer', 'verbose_name_plural': 'dependent performers'},
        ),
        migrations.AlterModelOptions(
            name='independentperformerprofile',
            options={'verbose_name': 'independent performer', 'verbose_name_plural': 'independent performers'},
        ),
        migrations.RemoveField(
            model_name='dependentperformerprofile',
            name='performance_class',
        ),
        migrations.RemoveField(
            model_name='dependentperformerprofile',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='performers',
        ),
        migrations.AddField(
            model_name='dependentperformerprofile',
            name='performance',
            field=models.ManyToManyField(to='performances.Performance'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='performances',
            field=models.ManyToManyField(related_name='performances_under_care', to='performances.Performance'),
        ),
        migrations.AlterField(
            model_name='dependentperformerprofile',
            name='institution',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='performances.institution'),
            preserve_default=False,
        ),
    ]
