# Generated by Django 3.1.6 on 2021-04-19 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0009_auto_20210419_1245'),
        ('accounts', '0006_auto_20210419_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependentperformerprofile',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='independentperformerprofile',
            name='institution',
        ),
        migrations.AddField(
            model_name='customuser',
            name='institution',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='performances.institution'),
            preserve_default=False,
        ),
    ]
