# Generated by Django 3.1.6 on 2021-04-20 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0009_auto_20210419_1245'),
        ('accounts', '0007_auto_20210419_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='institution',
        ),
        migrations.AddField(
            model_name='dependentperformerprofile',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='performances.institution'),
        ),
    ]
